#!/bin/bash
# spellchecker: ignore admindir showformat zstdcat

set -x
mkdir -p "$CRAFT_PRIME/usr/share/rocks/"

manifest_path="$CRAFT_PRIME/usr/share/rocks/dpkg.query"

echo "# os-release" > "$manifest_path"
cat /etc/os-release >> "$manifest_path"

echo "# dpkg-query" >> "$manifest_path"
{
    # include all packages in the system
    dpkg-query \
        --admindir="$CRAFT_PRIME/var/lib/dpkg/" \
        -f '${binary:Package}=${Version},${source:Package}=${Source:Version}\n' \
        -W

    # include all .deb files in stage_packages
    for deb in /root/parts/*/stage_packages/*.deb; do 
        # TODO: should we assume that all packages are installed correctly (ii)
        # shellcheck disable=SC2016
        dpkg-deb -W --showformat 'ii,${Package},${Version},,\n' "$deb "
    done
    # include all results from chisel manifest
    zstdcat "$CRAFT_STAGE/var/lib/chisel/manifest.wall" \
        | jq -r 'select(.kind == "package") | "ii," + .name + "," + .version + ",,"'

} | sort | uniq | tee -a "$manifest_path"
